// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1hGPvSxNOwIVEcFpmgrDT1tq9-M5qEl4',
    appId: '1:1089345643848:web:f1cabf9a9305754634ff7d',
    messagingSenderId: '1089345643848',
    projectId: 'trakon-65927',
    authDomain: 'trakon-65927.firebaseapp.com',
    storageBucket: 'trakon-65927.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJO6eP54Kvk4yygYxvzqfQT88KD6H_hg',
    appId: '1:1089345643848:android:7ad630a2ac09927c34ff7d',
    messagingSenderId: '1089345643848',
    projectId: 'trakon-65927',
    storageBucket: 'trakon-65927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jJtr2SV2H3omEbbrbM46llsGwLo3WdU',
    appId: '1:1089345643848:ios:c64e686b0852dbcd34ff7d',
    messagingSenderId: '1089345643848',
    projectId: 'trakon-65927',
    storageBucket: 'trakon-65927.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jJtr2SV2H3omEbbrbM46llsGwLo3WdU',
    appId: '1:1089345643848:ios:c64e686b0852dbcd34ff7d',
    messagingSenderId: '1089345643848',
    projectId: 'trakon-65927',
    storageBucket: 'trakon-65927.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1hGPvSxNOwIVEcFpmgrDT1tq9-M5qEl4',
    appId: '1:1089345643848:web:c146eabb5f2e311634ff7d',
    messagingSenderId: '1089345643848',
    projectId: 'trakon-65927',
    authDomain: 'trakon-65927.firebaseapp.com',
    storageBucket: 'trakon-65927.firebasestorage.app',
  );
}
